name: nushell github action $env by sh

on: 
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  basic-usage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: hustcer/setup-nu@main
        with:
          version: "*"
      - name: Run script
        run: |
          echo ${{ github.ref_name }}
          echo $GITHUB_REF_NAME