name: nushell github action $env

on: 
  workflow_dispatch:
    inputs:
      app:
        description: App to run workflow for. For multiple at ones separate the names with commas, for all leave default
        required: false
        default: "all"
  push:
    branches:
      - main
defaults:
  run:
    shell: nu {0}

jobs:
  basic-usage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: hustcer/setup-nu@main
        with:
          version: "*"
      - run: version; print $"(char nl)Dir contents:(char nl)"; ls ((which nu).path.0 | path dirname)
      - run: |
          print $'Current env:(char nl)'
          print $env
          echo "good=x" | save --append $env.GITHUB_OUTPUT
          open $env.GITHUB_OUTPUT
      - name: open all file
        run: |
            let cs = $env | columns
            mut fls = []
            for k in $cs {
                let v = $env | get  $k

                if (($v | describe -dn | get type) == 'string') {
                    if (((echo $v | path type) == 'file') and ((echo $v | path parse | get extension | into string) == 'json')) { 
                      $fls = ($fls | append $v)
                    } 
                  }
            }  
            $fls | each {|it| open $it | to json}
            open $env.GITHUB_OUTPUT
      - name: open /home/runner/work/_temp/_github_workflow/event.json
        run: |
          open /home/runner/work/_temp/_github_workflow/event.json
      - name: You can run bash commands, too
        run: pwd && ls -la
        shell: bash
      - name: filters files for generate
        id: generate-files
        env:
          app: ${{ inputs.app }}
        shell: nu {0}
        run: |
          use std log
          log info ($env | get GITHUB_EVENT_NAME)
          mut moduleNames = ""
          let eventName = ($env | get GITHUB_EVENT_NAME)
          log info ("Running workflow_dispatch, modules: " | append $eventName | str join '')
          if ((echo $eventName) == "workflow_dispatch") {
            log info ("Running workflow_dispatch, modules: " | append $env.app | str join '')
          }
          log info ("Running workflow_dispatch, modules: " | append $env.app | str join '')
          
      - name: push event
        if: ${{ github.event_name == 'push' }}
        run: |
          open ($env.GITHUB_EVENT_PATH)